# Generated by Django 2.2 on 2020-04-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='PhoneNumber',
        ),
    ]
